name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add SSH Key
      run: |
        echo "${{ secrets.EC2_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@54.147.155.215${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ec2-user/app
          git pull origin main
          npm install
          npm run build
          pm2 restart app || pm2 start npm --name "app" -- start
        EOF
